### PR TITLE
Removed Adam Bien as its feed url is broken

### PR DESCRIPTION
**Pull request by linkfang**
For [issue96](https://github.com/jakartaee/jakartablogs.ee/issues/96)

### CODE REVIEW

**Comment by alliancecoder** [comment]
https://adambien.blog/roller/

This is the correct URL

**Review by autumnfound — APPROVED** [review]

**Comment by autumnfound** [comment]
> https://adambien.blog/roller/
> 
> This is the correct URL

The URL that we store is the RSS feed source to be aggregated in the data feed. While that is his actual blog page, the RSS source is not available currently or has changed. Until we get the proper link, we remove the entries just for safety

**Comment by ivargrimstad** [comment]
Here's Adams RSS feed: https://www.adam-bien.com/roller/abien/feed/entries/rss

**Comment by chrisguindon** [comment]
> Here's Adams RSS feed: https://www.adam-bien.com/roller/abien/feed/entries/rss
> 
> or
> 
> https://adambien.blog/roller/abien/feed/entries/rss

I am getting an empty white page on both.

**Comment by ivargrimstad** [comment]
I get that in the browser as well, but `wget https://adambien.blog/roller/abien/feed/entries/rss` returns the xml feed

**Comment by chrisguindon** [comment]
I see and it seems that we are displaying posts from his blog on the site: https://jakartablogs.ee/#main-content

Let's close this for now.

**Pull request closed without merging**
